Vagrant.configure("2") do |config|
  config.vm.box = "fgrehm/wheezy64-lxc"
  config.vagrant.plugins = [ "vagrant-lxc" ]
  config.vm.provision :shell, inline: <<-SCRIPT
  apt-get update
  apt-get install stress -y
  SCRIPT
  config.vm.provider :lxc do |lxc|
    lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
    lxc.customize 'cgroup.cpuset.cpus', '1'
  end
end
