Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provision :shell, privileged: false, inline: <<-SCRIPT
  sudo apt update
  # Install some utils
  sudo apt install libltdl7 curl lxc lynx -y
  # Install vagrant
  curl --silent --remote-name 'https://releases.hashicorp.com/vagrant/2.1.5/vagrant_2.1.5_x86_64.deb'
  sudo dpkg -i vagrant_2.1.5_x86_64.deb
  # Install Docker
  curl --silent --remote-name 'https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb'
  sudo dpkg -i docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb
  SCRIPT
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 3
  end
end
